### ISSUE TITLE
Not all metrics are getting sent to graphite

### ISSUE THREAD

**Issue by Shadow00Caster** [unixsurfer/haproxystats#14]
It doesn't look like all the metrics are getting pushed into Graphite.  Metrics that should exist in many cases, such as scur (which always has a value in this case) do not appear, some servers do not appear.  It looks like letting it run metrics may eventually start to appear, but then that defeats the purpose, if the first process does not contain all metrics, then I would assume every process may not contain some data which makes it useless?

![image](https://user-images.githubusercontent.com/13611109/39827485-e5f50b38-536c-11e8-965c-d055208eca54.png)

**Comment by unixsurfer** [comment]
Could you please add **local-store** section in the `haproxystats.conf`and see if metrics are present in the files? Please read https://github.com/unixsurfer/haproxystats#local-store-section for more information.

**Comment by unixsurfer** [comment]
I would like to close this as I haven't seen any data supporting that we don't send metrics.
