### ISSUE TITLE
Replacing N/A with zero messes up an average

### ISSUE THREAD

**Issue by gringus** [unixsurfer/haproxystats#23]
Replacing N/A with zeros will incorrectly calculate an average:

https://github.com/unixsurfer/haproxystats/blob/c6a0bbccf4f4faaf3a307f2bb4a7d163c60fe422/haproxystats/process.py#L460

eg.

Values: 1, 2, 3, N/A, N/A
Without replacing N/As will get ignored and we will have: (1+2+3)/3 = 2
When replacing N/As with 0 we will have: (1+2+3+0+0)/5 = 1.2

**Comment by unixsurfer** [comment]
I see. We need to figure out how pandas dataframe will look like if we keep the null data points.
Can you provide an example of metrics that may return null?

**Comment by gringus** [comment]
Currently there's only one metric in HAProxy which can return no value (value is applied conditionally) and is calculated as an average (throttle), but I plan to convince Willy to get all timing metrics do the same as 0 != no data.
I suspect leaving N/A as-is shouldn't break processing an should make us more accurate.

**Comment by unixsurfer** [comment]
Sorry, I couldn't follow you. Are you saying that haproxy will return 0 and not N/A?

**Comment by gringus** [comment]
Currently HAProxy returns 0 (except throttle metric which returns empty string). Empty string is interpreted as N/A by Pandas.
I plan to convince Willy to return empty string for all moving average metrics (eg. ctime) if there is no data (currently this is not the case). This way you will be able to distinguish if your ctime is actually 0 or there haven't been any requests.

**Comment by unixsurfer** [comment]
I see, I agree that if we don't have data then we shouldn't pretend that we got something back by having haproxy returning 0. We should simply skip that data point.

**Comment by gringus** [comment]
Alternative:
Taking into account only timing metrics (eg. ctime, ttime) if req_tot/lbconn are non-zero. That's a bit tricky as for HTTP mode we need to use req_tot and for TCP mode lbconn. Looks like lbconn is incremented when new connection gets established and req_tot when request gets completed for HTTP requests. Sometimes this might take seconds between increment of lbconn and change of req_tot/ctime.
Not sure how difficult that would be to implement (if needed). I plan to send e-mail to HAProxy mailing list sometime this week.

**Comment by unixsurfer** [comment]
> Alternative:
> Taking into account only timing metrics (eg. ctime, ttime) if req_tot/lbconn are non-zero. That's a bit tricky as for HTTP mode we need to use req_tot and for TCP mode lbconn. Looks like lbconn is incremented when new connection gets established and req_tot when request gets completed for HTTP requests. Sometimes this might take seconds between increment of lbconn and change of req_tot/ctime.
> Not sure how difficult that would be to implement (if needed). I plan to send e-mail to HAProxy mailing list sometime this week.

This sounds so complicated that I wouldn't want to add it to haproxystats.

**Comment by gringus** [comment]
Unfortunately Willy did not accept an idea about not exposing metric even if there is no data available as it would potentially break scripts/other software which rely on the data (backward compatibility with past behavior).
Workaround code for the backend would look like this:
```
got_traffic = ((data_frame['req_tot'] > 0) | ((data_frame['mode'] != 'http') & (data_frame['lbtot'] > 0)))
stats_avg = (data_frame[is_backend & filter_backend & got_traffic]
```
For server things get more complicated as **req_tot** metric was just introduced and is empty in all previous versions of HAProxy, so probably we can only rely on **lbtot** in all cases (at least for the time being).
It's your call, feel free to close this issue if you don't like the idea.

**Comment by unixsurfer** [comment]
I briefly followed the thread in HAProxy mailing list and I fully understand Willy's approach.

I am not 100% sure if I want to support this logic as it adds complexity that may work against us at later stage.

**Comment by gringus** [comment]
```
got_traffic = (data_frame['lbtot'] > 0)
```
alone should not have huge impact on performance nor complexity of the code and work in all modes. It's not perfect (for HTTP requests there is a small window when _lbtot_ increases, but not _req_tot_), but already a significant step forward.

**Comment by unixsurfer** [comment]
Can you work a draft PR? I may find some time to look at it the coming week or during the weekend.

**Comment by gringus** [comment]
Sure. Will link it here..

**Comment by gringus** [comment]
[Pull request](https://github.com/unixsurfer/haproxystats/pull/24)
I have to admit I haven't tested this particular change although I have tested a bit more complex:
```
backend:
got_traffic = ((data_frame['req_tot'] > 0) | (data_frame['mode'].ne('http') & (data_frame['lbtot'] > 0)))
server:
got_traffic = ((data_frame['req_tot'] > 0) | ((data_frame['mode'].ne('http') | data_frame['req_tot'].isnull()) & (data_frame['lbtot'] > 0)))
```
and it worked as expected.
