### ISSUE TITLE
Support for Authentication for Stats Socket

### ISSUE THREAD

**Issue by shyampsunder2003** [unixsurfer/haproxystats#3]
Hey, looked through your readme, couldn't figure out how to let the script know of the credentials to access the stats socket data. Is there any such feature? Thanks

**Comment by unixsurfer** [comment]
No, we don't have that yet. May I ask why you are using authentication for the UNIX (stats) socket?

Please paste your config here and I will try to add support for authentication the coming days

**Comment by unixsurfer** [comment]
Can I have an example HAProxy config?

**Comment by unixsurfer** [comment]
BTW, a workaround could be to add the user which you use to run haproxstats into 'haproxy' group and use `mode 660` in `stats socket` option of HAProxy.

**Comment by unixsurfer** [comment]
Closing the issue as the reported never came back with configuration example
