### ISSUE TITLE
Add total backend members metric

### ISSUE THREAD

**Issue by gringus** [unixsurfer/haproxystats#4]
Currently HaProxy exposes only active members per backend (act metric). It would be nice to expose total amount of members in the backend. This would be useful to calculate percentage of members active for eg. monitoring system.

**Comment by unixsurfer** [comment]
I am having some troubles to get this done using Pandas. I will give it another try early next week.

**Comment by unixsurfer** [comment]
Here is a pandas code which can provide the total amount of servers in a backend

### Filter only server type rows from pandas dataframe

``` python
is_server = data_frame['type'] == 2
servers = data_frame[is_server].loc[:,['pxname', 'svname']]
```

### Group by pxname, so by backend name

``` python
server_groups = servers.groupby(['pxname'])
```

### Aggregate per unique row, as a single server appears multiple times (where haproxy is configured withh nbproc >1)

``` python
total_servers_per_backend = server_groups.agg({'svname': pandas.Series.nunique})
```

### Print counter per backend

``` python
for _, row in total_servers_per_backend.iterrows():
        print(_, row[0])
```
